<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-04-18T02:01:58 IST" name="Practice Suite" finished-at="2020-04-18T02:02:03 IST" duration-ms="4926">
    <groups>
      <group name="automationSuite">
        <method signature="TestCase.postCallTestCase()[pri:0, instance:testSuite.TestCase@c667f46]" name="postCallTestCase" class="testSuite.TestCase"/>
        <method signature="TestCase.deleteCallTestCase()[pri:0, instance:testSuite.TestCase@c667f46]" name="deleteCallTestCase" class="testSuite.TestCase"/>
      </group> <!-- automationSuite -->
    </groups>
    <test started-at="2020-04-18T02:01:58 IST" name="TestSuite" finished-at="2020-04-18T02:02:03 IST" duration-ms="4926">
      <class name="testSuite.TestCase">
        <test-method signature="postCallTestCase()[pri:0, instance:testSuite.TestCase@c667f46]" started-at="2020-04-18T02:01:58 IST" name="postCallTestCase" finished-at="2020-04-18T02:02:01 IST" duration-ms="3219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCallTestCase -->
        <test-method signature="deleteCallTestCase()[pri:0, instance:testSuite.TestCase@c667f46]" started-at="2020-04-18T02:02:01 IST" name="deleteCallTestCase" finished-at="2020-04-18T02:02:02 IST" depends-on-methods="testSuite.TestCase.postCallTestCase" duration-ms="1175" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [success] but found [failed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [success] but found [failed]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at apiHelper.TestCaseHelperFile.validateDeleteCallResponse(TestCaseHelperFile.java:76)
at testSuite.TestCase.deleteCallTestCase(TestCase.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCallTestCase -->
      </class> <!-- testSuite.TestCase -->
    </test> <!-- TestSuite -->
  </suite> <!-- Practice Suite -->
</testng-results>
