<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PNE-L-PG03" failures="1" tests="3" name="SlicePayTest" time="6.39" errors="0" timestamp="2020-04-18T01:25:52 IST">
  <testcase classname="testSuite.TestCase" name="postCallTestCase" time="3.992"/>
  <testcase classname="testSuite.TestCase" name="getCallTestCase" time="0.375"/>
  <testcase classname="testSuite.TestCase" name="deleteCallTestCase" time="1.389">
    <failure type="java.lang.AssertionError" message="expected [success] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [failed]
at apiHelper.TestCaseHelperFile.validateDeleteCallResponse(TestCaseHelperFile.java:78)
at testSuite.TestCase.deleteCallTestCase(TestCase.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteCallTestCase -->
</testsuite> <!-- SlicePayTest -->
